[package]
name = "ii-sensors"
version = "0.1.0"
authors = ["Braiins <braiins@braiins.com>"]
license = "GPL-3.0-or-later"
edition = "2018"

[dependencies]
async-trait = "0.1.24"
ii-async-compat = { path = "../../utils-rs/async-compat" }
